//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactSwarmService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public long Id { get; set; }
        public long TypeId { get; set; }
        public long PersonId { get; set; }
        public string Value { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ContactType Type { get; set; }
    }
}
